[FIX] base_optional_quick_create: add mail dependency
Fix

psycopg2.ProgrammingError: column ir_model.is_mail_activity does not exist
LINE 1: ...","ir_model"."is_mail_thread" as "is_mail_thread","ir_model"...

on upgrade from 12.0 to 13.0